### ISSUE TITLE
Potential dependency conflicts between azkaban and urllib3

### ISSUE THREAD

**Issue by NeolithEra** [mtth/azkaban#42] opened 2019-12-28 13:30 UTC
Hi, as shown in the following full dependency graph of  **_azkaban_**, **_azkaban_** requires **_urllib3  *_** ， while the installed version of **_requests_**(2.22.0) requires _**urllib3  <1.26,>=1.21.1**_.

According to Pip's _“first found wins”_ installation strategy, _**urllib3 1.25.7**_ is the actually installed version.  

Although the first found package version _**urllib3 1.25.7**_ just satisfies the later dependency constraint （_**urllib3  <1.26,>=1.21.1**_), it will lead to a build failure once developers release a newer version of urllib3.

### Dependency tree--------
```
azkaban - 0.9.13
| +- docopt(install version:0.6.2 version range:*)
| +- requests(install version:2.22.0 version range:>=2.4.0)
| | +- certifi(install version:2019.9.11 version range:>=2017.4.17) m
| | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | +- urllib3(install version:1.25.6 version range:<1.26,>=1.21.1)
| +- six(install version:1.13.0 version range:>=1.6.1)
| +- urllib3(install version:1.25.6 version range:*)
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment] 2019-12-28 13:31
### Suggested Solution

1.	Fix your direct dependencies to be **_urllib3  <1.26_**.
2.	Ask your upstream project **_request_** to losse the version range of **_urllib3_** to be **_>=1.21.1_**.

@mtth Which solution do you prefer, 1 or 2?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by mtth** [comment] 2019-12-28 13:58
Hi @NeolithEra, thanks for raising this.

> Fix your direct dependencies to be urllib3 <1.26.

This isn't a fix: it's a workaround for `pip`'s lack of global dependency resolution. Unfortunately it's not satisfactory. First, it's hard to maintain: we'd need to update the bound each time `requests` updates theirs. Second, it's confusing since `azkaban` doesn't actually require this upper bound.

> Ask your upstream project request to losse the version range of urllib3 to be >=1.21.1.

If that's possible, it sounds great. However, I suspect `requests` upper bounds the package to avoid breaking changes when new versions get released. This allows them to vet versions before including them.

Unfortunately, given `pip`'s features, I don't think there is a clean fix for this if option 2 is not possible. The best way to address this is for client packages to specify a [`requirements.txt`](https://pip.pypa.io/en/latest/user_guide/#requirements-files) file, which pins the version of all their dependencies. It's also good practice to enable reproducible builds.

**Closed** 2020-01-25 15:56 UTC
